# Generated by Django 3.2.7 on 2021-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecontent',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.RecipeContent', to='recipes.Ingredient'),
        ),
    ]
